apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sqldb
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: sqldbcontainer
          image: 632347313670.dkr.ecr.us-east-1.amazonaws.com/ecr_my_db:419a932