apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-sqldb
  labels:
    app: mysql
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: sqldb
          image: 632347313670.dkr.ecr.us-east-1.amazonaws.com/ecr_my_db:419a932
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
              protocol: TCP