apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: employees
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100
  selector:
    app: employees