apiVersion: v1
kind: Service
metadata:
  name: webappsvc
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees
    version: v1