apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: webapp
          image: 632347313670.dkr.ecr.us-east-1.amazonaws.com/ecr_my_app:419a932
          env:
            - name: DBHOST
              value: "sqldbsvc.sqldb"
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              valueFrom:
               secretKeyRef:
                 name: webapp-sql-secret
                 key: password
          ports:
            - containerPort: 8080
              protocol: TCP